name: Publish to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Configure npm for npmjs.org
        run: |
          echo "registry=https://registry.npmjs.org" > .npmrc

      - run: npm ci --legacy-peer-deps

      - run: npm run lint

      - run: npm run typecheck

      - run: npm run test:coverage

      - run: npm run build

      - name: Verify build outputs
        run: |
          test -f dist/index.js
          echo "✅ Build outputs verified"

      - run: npm publish --access public --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: |
            🎉 New release published to npm!

            ### Installation
            ```bash
            npm install claude-ops-mcp@${{ github.ref_name }}
            ```

            ### Usage
            See [README.md](https://github.com/pppp606/claude-ops-mcp#readme) for usage instructions.
          draft: false
          prerelease: false
